### ISSUE TITLE
Upper Limit Above 100 turns in error

### ISSUE THREAD

**Issue by FedericoOlivieri** [michaeldmoore/michaeldmoore-annunciator-panel#5]
Hello!
Thanks for your work done so far!
I have a problem when I set the upper limit above 100 (i.e.120) I get the error below (in this case lower limit is 90)
`
Annunciator Options Error
UpperWarning Value should be less than UpperLimit Value
`

Here the json body if can that help in some way

`{
  "LowerLimit": {
    "Color": "#bf1b00",
    "Decimals": 3,
    "DisplayOption": "static",
    "FontSize": "hide",
    "Value": "0"
  },
  "LowerWarning": {
    "Color": "rgb(9, 115, 102)",
    "DisplayOption": "disabled",
    "Value": "25"
  },
  "Metric": {
    "Color": "rgb(2, 247, 2)",
    "Decimals": 3,
    "FontSize": "150%",
    "Format": "ms",
    "Name": "current"
  },
  "MetricValueRange": "0 -> 90",
  "Postfix": {
    "FontSize": "hide",
    "Text": ""
  },
  "Prefix": {
    "FontSize": "hide",
    "Text": ""
  },
  "UpperLimit": {
    "Color": "#bf1b00",
    "Decimals": 3,
    "DisplayOption": "flash",
    "FontSize": "hide",
    "Value": "99"
  },
  "UpperWarning": {
    "Color": "#e0752d",
    "DisplayOption": "static",
    "Value": "90"
  },
  "datasource": "influxdb-eu-west-1a",
  "gridPos": {
    "h": 6,
    "w": 8,
    "x": 0,
    "y": 42
  },
  "id": 31,
  "links": [
    {
      "dashUri": "db/ping-ash",
      "dashboard": "PING - ASH",
      "includeVars": true,
      "keepTime": true,
      "targetBlank": true,
      "title": "PING - ASH",
      "type": "dashboard"
    }
  ],
  "sparkline": {
    "fillColor": "rgba(31, 118, 189, 0.18)",
    "full": false,
    "lineColor": "rgb(0, 25, 249)",
    "show": true
  },
  "targets": [
    {
      "alias": "atl.tmol.euash1.websys.tmcs",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "measurement": "ping_rtt",
      "orderByTime": "ASC",
      "policy": "default",
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": [
        {
          "key": "host",
          "operator": "=",
          "value": "atl.tmol.euash1.websys.tmcs"
        }
      ]
    }
  ],
  "title": "1A - atl.tmol.euash1.websys.tmcs",
  "type": "michaeldmoore-annunciator-panel"
}`

**Comment by michaeldmoore** [comment]
There are 4 limit values (all optional), lower limit, lower warning, upper
warning and upper limit.  The error says you are trying to set the upper
limit to a value below the upper warning - take a look and, if you don't
need a warning level - disable it.

Make sense?

**Comment by FedericoOlivieri** [comment]
In my scenario I would like to have:

Upper Warning 90
Upper Limit 120

When I try to configure that I get the error `Error UpperWarning Value should be less than UpperLimit`. But as we can see Upper Warning is less than Upper Limit. The only max value accepted on Upper Limit is 99. 

So, the below is ok
Upper Warning 90
Upper Limit 99

**Comment by michaeldmoore** [comment]
I understand, but the error makes no sense.

The validation occurs as you exit each text box, so maybe you need to set
the upper warning to 90 first, then set the upper limit to 120?

I'm on the road this week, so you are on you to own for a bit.

If in doubt, disable each of the limit/warnings and set them one at a time.
Good luck.  I've never found any issues with this, so it can't be too
messed up.


On Sep 25, 2018 9:15 AM, "Federico87" <notifications@github.com> wrote:

In my scenario I would like to have:

Upper Warning 90
Upper Limit 120

When I try to configure that I get the error Error UpperWarning Value
should be less than UpperLimit. But as we can see Upper Warning is less
than Upper Limit. The only max value accepted on Upper Limit is 99.

So, the below is ok
Upper Warning 90
Upper Limit 99

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/michaeldmoore/michaeldmoore-annunciator-panel/issues/5#issuecomment-424383131>,
or mute the thread
